[package]
name = "tree-sitter-goto-first-child-for-byte-sanity-check"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter = "0.20.10"
tree-sitter-javascript = "0.20.0"
